version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
      - static_volume/:/usr/src/app/static/
      - media_volume/:/usr/src/app/media/
    restart: always
    ports:
    - "8000:8000"

volumes:
  postgres_data:
  static_volume:
  media_volume:
